spring:
  main:
    # 禁用banner
    banner-mode: off

logging:
  charset:
    file: UTF-8
  file:
    path: /log

  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      total-size-cap: 0B
      max-history: 7
